#baseURL = "www.roule.net"
baseURL = "" # www.roule.net"
languageCode = "en-us"
title = "Roule"
theme = "meghna-hugo"
summaryLength = 4

[permalinks]
  post = " "

[taxonomies]
  author = "Dugongs"
  category = "categories"
  tag = "tags"

# Menu
[menu]
    [[menu.nav]]
    name = "Aujourd'hui"
    URL = "today"
    weight = 2

    [[menu.nav]]
    name = "Les prochains jours"
    URL = "forecast"
    weight = 3

    [[menu.nav]]
    name = "Contact"
    URL = "contact-us"
    weight = 8

# Site params
[params]
home= "Home"
logo = "images/logo.png"
#gmapAPI = "https://maps.googleapis.com/maps/api/js?key=AIzaSyCcABaamniA6OL5YvYSpB3pFMNrXwXnLwU&libraries=places"
# Meta data
description = "Services pour le velotaf"
author = "The Dugong team"
# Google Analitycs
googleAnalitycsID = "Your ID"
custom_css = ["css/custom.css"]

    # Banner Section
    [params.banner]
    enable = true
    bgImage = "images/slider/hero-area.jpg"
    icon = "tf-ion-play"
    heading = "Bienvenuie sur roule.net"
    content= "Services pour le velotaf"
    #btn = Flase
    #btnText="Explore Us"
    #btnURL="#services"

    ## call to action
    #[params.cta]
    #enable = true
    #title = "Great Design & Incredible Features"
    #content = "Lorem ipsum dolor sit amet consectetur adipisicing elit. Officiis tenetur odio impedit incidunt? Omnis accusantium ea reiciendis, fugit commodi nostrum."
    #btnURL = "#"
    #btnText = "Start a project with us"

    # counter
    [params.counter]
    enable = true
    bgImage = "images/backgrounds/bg-1.jpg"
        [[params.counter.counterItem]]
        title = "Temperatures"
        icon = "tf-ion-android-happy"
        count = "Douces"

        [[params.counter.counterItem]]
        title = "Precipitations"
        icon = "tf-ion-thumbsup"
        count = "Importantes"

        [[params.counter.counterItem]]
        title = "Qualité air"
        icon = "tf-ion-archive"
        count = "Bonne"

    # Footer Section
    [params.footer]
    enable = true
    copyright = "Team Dugong"
